spring:
  profiles: dev
  application:
    name: trading-app
  h2:
    console:
      enabled: true
      
spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL
   
server:
  port: 8080
  

  
---

spring:
  profiles: prod
  application:
    name: trading-app
   
server:
  port: 8081